name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Set environment variable for database path
        run: echo "DB_PATH=$GITHUB_WORKSPACE/data/todos.sqlite" >> $GITHUB_ENV

      - name: Run tests
        env:
          DB_PATH: ${{ env.DB_PATH }}  # Use the environment variable in tests
        run: npm test

      - name: Build project
        run: npm run build

      - name: Echo your name
        run: echo "This workflow was triggered by ${USER_NAME}"
        env:
          USER_NAME: ${{ github.actor }}  # Use the GitHub actor as the user name

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy code
        run: echo "Deploying application..."

      - name: GitHub API Request with Token
        run: |
          echo "Using GitHub token for authentication"
          # Example API request using GitHub Token
          curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/user/repos
